---
abstract: 'Like the setlock command using Redis.'
author:
  - 'FUJIWARA Shunichiro <fujiwara.shunichiro@gmail.com>'
build_requires:
  Net::EmptyPort: 0
  Test::More: 0.98
  Test::RedisServer: 0
  Test::SharedFork: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.8.0, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Redis-Setlock
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Redis::Setlock:
    file: lib/Redis/Setlock.pm
    version: 0.03
requires:
  Getopt::Long: 2.42
  Guard: 0
  Log::Minimal: 0
  Pod::Usage: 0
  Redis: 0
  Time::HiRes: 0
  Try::Tiny: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/fujiwara/Redis-Setlock/issues
  homepage: https://github.com/fujiwara/Redis-Setlock
  repository: git://github.com/fujiwara/Redis-Setlock.git
version: 0.03
